services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "3010:3000"
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: /bin/sh -c 'if [ -n "$REDIS_PASSWORD" ]; then redis-server --requirepass $REDIS_PASSWORD; else exit 1; fi'
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
